In [1]:
import os
import torch
import pandas as pd
from modules.feature_engineering import FeatureEngineeringV1 
from modules.data_module import FlightDataModule
from modules.training import TrainingFlightModel
from lightning.pytorch.callbacks import ModelCheckpoint, EarlyStopping
from lightning.pytorch.loggers import TensorBoardLogger

print(torch.__version__)
fe = FeatureEngineeringV1()

2.1.2+cu121


In [2]:
%load_ext tensorboard

In [3]:
def get_default_device():
    """Pick GPU if available, else CPU"""
    if torch.cuda.is_available():
        print(f'Using device: {torch.cuda.get_device_name(0)}')
        return torch.device('cuda')
    elif torch.backends.mps.is_available():
        print('Using device: Apple ARM GPU')
        return torch.device('mps')
    else:
        print('Using device: CPU')
        return torch.device('cpu')
    
# Set the device
device = get_default_device()
print(f'Using device: {device}')

Using device: NVIDIA GeForce RTX 3060
Using device: cuda


In [4]:
# Used with GPUs having Tensor cores
torch.set_float32_matmul_precision('medium')

In [5]:
processed_df = pd.read_csv('../data/csv/processed.csv')
processed_df

wind_speed_TSN  wind_dir_TSN  wind_speed_KADUM  wind_dir_KADUM  \
0            0.630435      0.363611          0.200000        0.361868   
1            0.630435      0.363611          0.200000        0.362146   
2            0.630435      0.363611          0.200000        0.362146   
3            0.630435      0.363611          0.200000        0.362424   
4            0.630435      0.363611          0.200000        0.362424   
...               ...           ...               ...             ...   
60523        0.347826      0.381111          0.327273        0.118121   
60524        0.347826      0.381111          0.327273        0.118121   
60525        0.347826      0.381111          0.327273        0.117009   
60526        0.347826      0.381111          0.327273        0.117009   
60527        0.347826      0.381389          0.327273        0.116176   

       wind_speed_PATNA  wind_dir_PATNA  wind_speed_SADAS  wind_dir_SADAS  \
0              0.229167        0.561418          0.014493        0.993860   
1              0.229167        0.562535          0.014493        0.994628   
2              0.229167        0.562535          0.014493        0.994628   
3              0.229167        0.563652          0.000000        0.996163   
4              0.229167        0.563652          0.000000        0.996163   
...                 ...             ...               ...             ...   
60523          0.531250        0.101619          0.391304        0.629317   
60524          0.531250        0.101619          0.391304        0.629317   
60525          0.531250        0.101619          0.391304        0.629317   
60526          0.531250        0.101619          0.391304        0.629317   
60527          0.531250        0.101340          0.391304        0.629317   

       wind_speed_DADEN  wind_dir_DADEN  ...  Route        Ac_id  Ac_code  \
0              0.150000        0.884247  ...      6  R6-VJ150-21    VJ150   
1              0.150000        0.882877  ...      6  R6-VJ150-21    VJ150   
2              0.150000        0.882877  ...      6  R6-VJ150-21    VJ150   
3              0.150000        0.882192  ...      6  R6-VJ150-21    VJ150   
4              0.150000        0.882192  ...      6  R6-VJ150-21    VJ150   
...                 ...             ...  ...    ...          ...      ...   
60523          0.533333        0.580822  ...      6  R6-VN258-04    VN258   
60524          0.533333        0.580822  ...      6  R6-VN258-04    VN258   
60525          0.533333        0.580822  ...      6  R6-VN258-04    VN258   
60526          0.533333        0.580822  ...      6  R6-VN258-04    VN258   
60527          0.533333        0.580822  ...      6  R6-VN258-04    VN258   

       Ac_type    Ac_kts  Time_step  Phase    Ac_Lat    Ac_Lon   Ac_feet  
0            1  0.060280          3      1  0.034167  0.454558  0.012828  
1            1  0.069968         23      1  0.033625  0.449206  0.032376  
2            1  0.097955         43      1  0.033203  0.443202  0.041539  
3            1  0.125942         59      1  0.033515  0.437884  0.047037  
4            1  0.151776         75      1  0.034810  0.433389  0.058033  
...        ...       ...        ...    ...       ...       ...       ...  
60523        2  0.046286       5344      1  0.993293  0.126874  0.040929  
60524        2  0.040904       5362      1  0.992935  0.131472  0.034820  
60525        2  0.034446       5378      1  0.992641  0.135280  0.029933  
60526        2  0.018299       5412      1  0.992090  0.142485  0.020770  
60527        2  0.025834       5480      1  0.990941  0.157340  0.001222  

[60528 rows x 46 columns]

In [6]:
X, y = fe.padding_features(processed_df)
print(f'X.shape: {X.shape}')
print(f'y.shape: {y.shape}')
print(f'X.dtype: {X.dtype}')
print(f'y.dtype: {y.dtype}')
print(f'X:\n{X}')
print(f'y:\n{y}')

X.shape: (352, 6616, 36)
y.shape: (352, 6616, 4)
X.dtype: float64
y.dtype: float64
X:
[[[0.63043478 0.36361111 0.2        ... 0.00833333 0.49230769 0.93388889]
  [0.63043478 0.36361111 0.2        ... 0.00833333 0.49230769 0.93361111]
  [0.63043478 0.36361111 0.2        ... 0.00833333 0.49230769 0.93361111]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[0.7173913  0.36138889 0.27272727 ... 0.00361111 0.49230769 0.93388889]
  [0.7173913  0.36138889 0.27272727 ... 0.00361111 0.49230769 0.93388889]
  [0.7173913  0.36138889 0.27272727 ... 0.00333333 0.49230769 0.93388889]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[0.63043

In [7]:
X_train, X_val, X_test, y_train, y_val, y_test = fe.split_train_test(X, y, test_size=0.2, val_size=0.25)
print(f'Shape of training set is {X_train.shape}, {y_train.shape}')
print(f'Shape of validation set is {X_val.shape}, {y_val.shape}')
print(f'Shape of test set is {X_test.shape}, {y_test.shape}')

Shape of training set is (281, 6616, 36), (281, 6616, 4)
Shape of validation set is (53, 6616, 36), (53, 6616, 4)
Shape of test set is (18, 6616, 36), (18, 6616, 4)


In [8]:
train_dataset, val_dataset, test_dataset = fe.make_tensor_dataset(X_train, X_val, X_test, y_train, y_val, y_test)
print(f'training set is {train_dataset}')
print(f'validation set is {val_dataset}')
print(f'test set is {test_dataset}')

training set is <torch.utils.data.dataset.TensorDataset object at 0x7fce24034c50>
validation set is <torch.utils.data.dataset.TensorDataset object at 0x7fce23f9ec90>
test set is <torch.utils.data.dataset.TensorDataset object at 0x7fce240344d0>


# TRAINING

---

In [9]:
# Global variables
batch_size_variable = 16
max_epochs = 200

In [10]:
flight_dm = FlightDataModule(train_dataset, val_dataset, test_dataset, batch_size=batch_size_variable)

In [11]:
model_name = 'flight_model_LSTM_V1'
base_dir = os.getcwd().replace('notebook', '')
log_dir = os.path.join(base_dir, 'log')
ckpt_dir = os.path.join(base_dir, model_name)
os.makedirs(log_dir, exist_ok=True)

In [12]:
log_dir

'/mnt/e/Work/chi_phuong_co_su/log'

In [13]:
# Some necessary callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=10, verbose=True, mode='min')
model_checkpoint = ModelCheckpoint(
    dirpath=log_dir,
    filename='LSTM-{epoch}-{val_loss:.5f}',
    monitor='val_loss', 
    save_top_k=3, 
    verbose=True, 
    mode='min'
)
logger = TensorBoardLogger(log_dir, name=model_name, log_graph=True)

In [14]:
training_module = TrainingFlightModel(
    early_stopping_lstm = early_stopping,
    model_checkpoint_lstm = model_checkpoint,
    logger_lstm = logger,
    data_module = flight_dm,
    max_epoch=max_epochs,
)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [15]:
training_module.training(
    input_size=36, 
    hidden_size=300, 
    num_layers=10,
    output_size=4, 
    learning_rate=1e-4,
    dropout=0.1,
)

Missing logger folder: /mnt/e/Work/chi_phuong_co_su/log/flight_model_LSTM_V0
/home/anvutrong/miniconda3/envs/wsl_env/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:653: Checkpoint directory /mnt/e/Work/chi_phuong_co_su/log exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name | Type             | Params | In sizes                                    | Out sizes                                   
---------------------------------------------------------------------------------------------------------------------------------------
0 | lstm | LSTM             | 3.3 M  | [[1, 6616, 36], [[5, 1, 300], [5, 1, 300]]] | [[1, 6616, 300], [[5, 1, 300], [5, 1, 300]]]
1 | fc   | Linear           | 1.2 K  | [1, 6616, 300]                              | [1, 6616, 4]                                
2 | loss | MSELoss          | 0      | ?                                           | ?                                           
3 | mse  | MeanSquaredE

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved. New best score: 0.008
Epoch 0, global step 18: 'val_loss' reached 0.00828 (best 0.00828), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=0-val_loss=0.01.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.008
Epoch 1, global step 36: 'val_loss' reached 0.00812 (best 0.00812), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=1-val_loss=0.01.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.008
Epoch 2, global step 54: 'val_loss' reached 0.00808 (best 0.00808), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=2-val_loss=0.01.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.008
Epoch 3, global step 72: 'val_loss' reached 0.00797 (best 0.00797), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=3-val_loss=0.01.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.008
Epoch 4, global step 90: 'val_loss' reached 0.00756 (best 0.00756), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=4-val_loss=0.01.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.002 >= min_delta = 0.0. New best score: 0.005
Epoch 5, global step 108: 'val_loss' reached 0.00532 (best 0.00532), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=5-val_loss=0.01.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.003 >= min_delta = 0.0. New best score: 0.002
Epoch 6, global step 126: 'val_loss' reached 0.00239 (best 0.00239), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=6-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 7, global step 144: 'val_loss' reached 0.00221 (best 0.00221), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=7-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 8, global step 162: 'val_loss' reached 0.00216 (best 0.00216), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=8-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 9, global step 180: 'val_loss' reached 0.00216 (best 0.00216), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=9-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 10, global step 198: 'val_loss' reached 0.00215 (best 0.00215), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=10-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 11, global step 216: 'val_loss' reached 0.00215 (best 0.00215), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=11-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 12, global step 234: 'val_loss' reached 0.00215 (best 0.00215), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=12-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 13, global step 252: 'val_loss' reached 0.00215 (best 0.00215), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=13-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 14, global step 270: 'val_loss' reached 0.00215 (best 0.00215), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=14-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 15, global step 288: 'val_loss' reached 0.00215 (best 0.00215), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=15-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 16, global step 306: 'val_loss' reached 0.00215 (best 0.00215), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=16-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 17, global step 324: 'val_loss' reached 0.00215 (best 0.00215), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=17-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 18, global step 342: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=18-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 19, global step 360: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=19-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 20, global step 378: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=20-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 21, global step 396: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=21-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 22, global step 414: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=22-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 23, global step 432: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=23-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 24, global step 450: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=24-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 25, global step 468: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=25-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 26, global step 486: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=26-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 27, global step 504: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=27-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 28, global step 522: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=28-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 29, global step 540: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=29-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 30, global step 558: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=30-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 31, global step 576: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=31-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 32, global step 594: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=32-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 33, global step 612: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=33-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 34, global step 630: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=34-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 35, global step 648: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=35-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 36, global step 666: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=36-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 37, global step 684: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=37-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 38, global step 702: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=38-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 39, global step 720: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=39-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 40, global step 738: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=40-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 41, global step 756: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=41-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 42, global step 774: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=42-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 43, global step 792: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=43-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 44, global step 810: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 45, global step 828: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 46, global step 846: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=46-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 47, global step 864: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 48, global step 882: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=48-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 49, global step 900: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=49-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 50, global step 918: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=50-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved by 0.000 >= min_delta = 0.0. New best score: 0.002
Epoch 51, global step 936: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=51-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 52, global step 954: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=52-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 53, global step 972: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 54, global step 990: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 55, global step 1008: 'val_loss' reached 0.00214 (best 0.00214), saving model to '/mnt/e/Work/chi_phuong_co_su/log/epoch=55-val_loss=0.00.ckpt' as top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 56, global step 1026: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 57, global step 1044: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 58, global step 1062: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 59, global step 1080: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 60, global step 1098: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 61, global step 1116: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 62, global step 1134: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 63, global step 1152: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 64, global step 1170: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 65, global step 1188: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 66, global step 1206: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 67, global step 1224: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 68, global step 1242: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 69, global step 1260: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 70, global step 1278: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 71, global step 1296: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 72, global step 1314: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 73, global step 1332: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 74, global step 1350: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 75, global step 1368: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 76, global step 1386: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 77, global step 1404: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 78, global step 1422: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 79, global step 1440: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 80, global step 1458: 'val_loss' was not in top 3


Validation: |          | 0/? [00:00<?, ?it/s]

Monitored metric val_loss did not improve in the last 30 records. Best score: 0.002. Signaling Trainer to stop.
Epoch 81, global step 1476: 'val_loss' was not in top 3


In [16]:
training_module.validate_and_testing_lstm(data_module=flight_dm)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Validation: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃      Validate metric      ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│      val_loss_epoch       │   0.002143095014616847    │
│       val_mse_epoch       │   0.002143095014616847    │
└───────────────────────────┴───────────────────────────┘

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│      test_loss_epoch      │   0.002164205303415656    │
│      test_mse_epoch       │   0.002164205303415656    │
└───────────────────────────┴───────────────────────────┘

In [18]:
# Tensorboard
%tensorboard --logdir /mnt/e/Work/chi_phuong_co_su/log

Reusing TensorBoard on port 6007 (pid 236788), started 4:22:22 ago. (Use '!kill 236788' to kill it.)