In [1]:
import pandas as pd
import torch
from modules.feature_engineering import FeatureEngineeringV1 
print(torch.__version__)

fe = FeatureEngineeringV1()

2.1.2+cu121


In [2]:
def get_default_device():
    """Pick GPU if available, else CPU"""
    if torch.cuda.is_available():
        print(f'Using device: {torch.cuda.get_device_name(0)}')
        return torch.device('cuda')
    elif torch.backends.mps.is_available():
        print('Using device: Apple ARM GPU')
        return torch.device('mps')
    else:
        print('Using device: CPU')
        return torch.device('cpu')
    
# Set the device
device = get_default_device()
print(f'Using device: {device}')

Using device: NVIDIA GeForce RTX 3060
Using device: cuda


In [3]:
processed_df = pd.read_csv('../data/csv/processed.csv')
processed_df

wind_speed_TSN  wind_dir_TSN  wind_speed_KADUM  wind_dir_KADUM  \
0            0.630435      0.363611          0.200000        0.361868   
1            0.630435      0.363611          0.200000        0.362146   
2            0.630435      0.363611          0.200000        0.362146   
3            0.630435      0.363611          0.200000        0.362424   
4            0.630435      0.363611          0.200000        0.362424   
...               ...           ...               ...             ...   
60525        0.347826      0.381111          0.327273        0.118121   
60526        0.347826      0.381111          0.327273        0.118121   
60527        0.347826      0.381111          0.327273        0.117009   
60528        0.347826      0.381111          0.327273        0.117009   
60529        0.347826      0.381389          0.327273        0.116176   

       wind_speed_PATNA  wind_dir_PATNA  wind_speed_SADAS  wind_dir_SADAS  \
0              0.229167        0.561418          0.014493        0.993860   
1              0.229167        0.562535          0.014493        0.994628   
2              0.229167        0.562535          0.014493        0.994628   
3              0.229167        0.563652          0.000000        0.996163   
4              0.229167        0.563652          0.000000        0.996163   
...                 ...             ...               ...             ...   
60525          0.531250        0.101619          0.391304        0.629317   
60526          0.531250        0.101619          0.391304        0.629317   
60527          0.531250        0.101619          0.391304        0.629317   
60528          0.531250        0.101619          0.391304        0.629317   
60529          0.531250        0.101340          0.391304        0.629317   

       wind_speed_DADEN  wind_dir_DADEN  ...  Route        Ac_id  Ac_code  \
0              0.150000        0.884247  ...      6  R6-VJ150-21    VJ150   
1              0.150000        0.882877  ...      6  R6-VJ150-21    VJ150   
2              0.150000        0.882877  ...      6  R6-VJ150-21    VJ150   
3              0.150000        0.882192  ...      6  R6-VJ150-21    VJ150   
4              0.150000        0.882192  ...      6  R6-VJ150-21    VJ150   
...                 ...             ...  ...    ...          ...      ...   
60525          0.533333        0.580822  ...      6  R6-VN258-04    VN258   
60526          0.533333        0.580822  ...      6  R6-VN258-04    VN258   
60527          0.533333        0.580822  ...      6  R6-VN258-04    VN258   
60528          0.533333        0.580822  ...      6  R6-VN258-04    VN258   
60529          0.533333        0.580822  ...      6  R6-VN258-04    VN258   

       Ac_type  Ac_kts  Time_step  Phase    Ac_Lat    Ac_Lon   Ac_feet  
0            1   170.0          3      1 -0.931666 -0.090884  0.012828  
1            1   179.0         23      1 -0.932750 -0.101588  0.032376  
2            1   205.0         43      1 -0.933595 -0.113597  0.041539  
3            1   231.0         59      1 -0.932970 -0.124232  0.047037  
4            1   255.0         75      1 -0.930379 -0.133221  0.058033  
...        ...     ...        ...    ...       ...       ...       ...  
60525        2   157.0       5344      1  0.986587 -0.746252  0.040929  
60526        2   152.0       5362      1  0.985870 -0.737057  0.034820  
60527        2   146.0       5378      1  0.985282 -0.729440  0.029933  
60528        2   131.0       5412      1  0.984180 -0.715031  0.020770  
60529        2   138.0       5480      1  0.981883 -0.685319  0.001222  

[60530 rows x 46 columns]

In [4]:
X, y = fe.padding_features(processed_df)
print(f'X.shape: {X.shape}')
print(f'y.shape: {y.shape}')
print(f'X.dtype: {X.dtype}')
print(f'y.dtype: {y.dtype}')
print(f'X:\n{X}')
print(f'y:\n{y}')

X.shape: (352, 6616, 36)
y.shape: (352, 6616, 4)
X.dtype: float64
y.dtype: float64
X:
[[[0.63043478 0.36361111 0.2        ... 0.00833333 0.49230769 0.93388889]
  [0.63043478 0.36361111 0.2        ... 0.00833333 0.49230769 0.93361111]
  [0.63043478 0.36361111 0.2        ... 0.00833333 0.49230769 0.93361111]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[0.7173913  0.36138889 0.27272727 ... 0.00361111 0.49230769 0.93388889]
  [0.7173913  0.36138889 0.27272727 ... 0.00361111 0.49230769 0.93388889]
  [0.7173913  0.36138889 0.27272727 ... 0.00333333 0.49230769 0.93388889]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[0.63043

In [5]:
X_train, X_val, X_test, y_train, y_val, y_test = fe.split_train_test(X, y, test_size=0.2, val_size=0.25)
print(f'Shape of training set is {X_train.shape}, {y_train.shape}')
print(f'Shape of validation set is {X_val.shape}, {y_val.shape}')
print(f'Shape of test set is {X_test.shape}, {y_test.shape}')

Shape of training set is (281, 6616, 36), (281, 6616, 4)
Shape of validation set is (53, 6616, 36), (53, 6616, 4)
Shape of test set is (18, 6616, 36), (18, 6616, 4)


In [8]:
train_dataset, val_dataset, test_dataset = fe.make_tensor_dataset(X_train, X_val, X_test, y_train, y_val, y_test)
print(f'training set is {train_dataset}')
print(f'validation set is {val_dataset}')
print(f'test set is {test_dataset}')

training set is <torch.utils.data.dataset.TensorDataset object at 0x7f1755d5ead0>
validation set is <torch.utils.data.dataset.TensorDataset object at 0x7f16781ea250>
test set is <torch.utils.data.dataset.TensorDataset object at 0x7f16781e9910>
